version: '3.7'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: reports_user
      POSTGRES_PASSWORD: angel_12345
      POSTGRES_DB: reports_db
    ports:
      - "5436:5432"
  bot:
    build: .
    command: sh -c "python -m main"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db